<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita47f2fde3bc89b21c11fd5b8d8e90a0c
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'VK\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'VK\\' => 
        array (
            0 => __DIR__ . '/..' . '/vkcom/vk-php-sdk/src/VK',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita47f2fde3bc89b21c11fd5b8d8e90a0c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita47f2fde3bc89b21c11fd5b8d8e90a0c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
